services:
  postgres:
    image: postgres
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"